package org.oremif.deepseek.models

import kotlinx.serialization.Serializable

/**
 * A chat completion delta generated by streamed model responses.
 *
 * Each streaming chunk's [ChatChoiceChunk.delta] carries only the fields that changed
 * on this step. Clients reconstruct the full assistant message by concatenating
 * [content] and [reasoningContent] across chunks, and by merging [toolCalls] by
 * [ToolCallDelta.index].
 *
 * @property role The role of the author of this message. Typically present only on
 * the first chunk of a response.
 * @property content Incremental content produced by the model on this step, if any.
 * @property reasoningContent For the `deepseek-reasoner` model: incremental reasoning
 * content produced on this step, if any.
 * @property toolCalls Incremental tool call updates produced on this step, if any.
 */
@Serializable
public class ChatCompletionDelta(
    public val role: String? = null,
    public val content: String? = null,
    public val reasoningContent: String? = null,
    public val toolCalls: List<ToolCallDelta>? = null,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is ChatCompletionDelta) return false
        return role == other.role &&
                content == other.content &&
                reasoningContent == other.reasoningContent &&
                toolCalls == other.toolCalls
    }

    override fun hashCode(): Int {
        var result = role?.hashCode() ?: 0
        result = 31 * result + (content?.hashCode() ?: 0)
        result = 31 * result + (reasoningContent?.hashCode() ?: 0)
        result = 31 * result + (toolCalls?.hashCode() ?: 0)
        return result
    }

    override fun toString(): String =
        "ChatCompletionDelta(role=$role, content=$content, reasoningContent=$reasoningContent, toolCalls=$toolCalls)"
}

/**
 * An incremental tool call update sent in a streaming chat completion response.
 *
 * Deltas for the same tool call share the same [index]. The first chunk for a given
 * tool call typically carries [id], [type] and [FunctionDelta.name]; subsequent
 * chunks append fragments of [FunctionDelta.arguments] in arrival order.
 *
 * @property index The position of the tool call in the full tool call list; used to
 * group deltas that belong to the same call.
 * @property id The ID of the tool call. Typically present only on the first chunk
 * for this [index].
 * @property type The type of the tool. Typically present only on the first chunk
 * for this [index].
 * @property function Partial function call information for this step.
 */
@Serializable
public class ToolCallDelta(
    public val index: Int,
    public val id: String? = null,
    public val type: ToolCallType? = null,
    public val function: FunctionDelta? = null,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is ToolCallDelta) return false
        return index == other.index &&
                id == other.id &&
                type == other.type &&
                function == other.function
    }

    override fun hashCode(): Int {
        var result = index.hashCode()
        result = 31 * result + (id?.hashCode() ?: 0)
        result = 31 * result + (type?.hashCode() ?: 0)
        result = 31 * result + (function?.hashCode() ?: 0)
        return result
    }

    override fun toString(): String =
        "ToolCallDelta(index=$index, id=$id, type=$type, function=$function)"
}

/**
 * A partial function call carried inside a [ToolCallDelta].
 *
 * @property name The name of the function to call. Typically present only on the
 * first chunk for its parent [ToolCallDelta.index].
 * @property arguments A fragment of the JSON-encoded function arguments.
 * Concatenate fragments in arrival order (grouped by [ToolCallDelta.index]) to
 * reconstruct the full arguments string, then parse as JSON.
 */
@Serializable
public class FunctionDelta(
    public val name: String? = null,
    public val arguments: String? = null,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is FunctionDelta) return false
        return name == other.name && arguments == other.arguments
    }

    override fun hashCode(): Int {
        var result = name?.hashCode() ?: 0
        result = 31 * result + (arguments?.hashCode() ?: 0)
        return result
    }

    override fun toString(): String =
        "FunctionDelta(name=$name, arguments=$arguments)"
}
