package org.oremif.deepseek.models

import kotlinx.serialization.Serializable

/**
 * @property reasoningTokens Tokens generated by the model for reasoning.
 */
@Serializable
public class CompletionTokenDetails(
    public val reasoningTokens: Int,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is CompletionTokenDetails) return false
        return reasoningTokens == other.reasoningTokens
    }

    override fun hashCode(): Int {
        return reasoningTokens.hashCode()
    }

    override fun toString(): String =
        "CompletionTokenDetails(reasoningTokens=$reasoningTokens)"
}